"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthLoginPostRequest = instanceOfAuthLoginPostRequest;
exports.AuthLoginPostRequestFromJSON = AuthLoginPostRequestFromJSON;
exports.AuthLoginPostRequestFromJSONTyped = AuthLoginPostRequestFromJSONTyped;
exports.AuthLoginPostRequestToJSON = AuthLoginPostRequestToJSON;
exports.AuthLoginPostRequestToJSONTyped = AuthLoginPostRequestToJSONTyped;
/**
 * Check if a given object implements the AuthLoginPostRequest interface.
 */
function instanceOfAuthLoginPostRequest(value) {
    return true;
}
function AuthLoginPostRequestFromJSON(json) {
    return AuthLoginPostRequestFromJSONTyped(json, false);
}
function AuthLoginPostRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}
function AuthLoginPostRequestToJSON(json) {
    return AuthLoginPostRequestToJSONTyped(json, false);
}
function AuthLoginPostRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'username': value['username'],
        'password': value['password'],
    };
}
