/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthhandlerLoginErrorResponseData
 */
export interface AuthhandlerLoginErrorResponseData {
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerLoginErrorResponseData
     */
    token?: string;
}

/**
 * Check if a given object implements the AuthhandlerLoginErrorResponseData interface.
 */
export function instanceOfAuthhandlerLoginErrorResponseData(value: object): value is AuthhandlerLoginErrorResponseData {
    return true;
}

export function AuthhandlerLoginErrorResponseDataFromJSON(json: any): AuthhandlerLoginErrorResponseData {
    return AuthhandlerLoginErrorResponseDataFromJSONTyped(json, false);
}

export function AuthhandlerLoginErrorResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthhandlerLoginErrorResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

  export function AuthhandlerLoginErrorResponseDataToJSON(json: any): AuthhandlerLoginErrorResponseData {
      return AuthhandlerLoginErrorResponseDataToJSONTyped(json, false);
  }

  export function AuthhandlerLoginErrorResponseDataToJSONTyped(value?: AuthhandlerLoginErrorResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

