/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthhandlerRegisterRequest
 */
export interface AuthhandlerRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerRegisterRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerRegisterRequest
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerRegisterRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerRegisterRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the AuthhandlerRegisterRequest interface.
 */
export function instanceOfAuthhandlerRegisterRequest(value: object): value is AuthhandlerRegisterRequest {
    return true;
}

export function AuthhandlerRegisterRequestFromJSON(json: any): AuthhandlerRegisterRequest {
    return AuthhandlerRegisterRequestFromJSONTyped(json, false);
}

export function AuthhandlerRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthhandlerRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

  export function AuthhandlerRegisterRequestToJSON(json: any): AuthhandlerRegisterRequest {
      return AuthhandlerRegisterRequestToJSONTyped(json, false);
  }

  export function AuthhandlerRegisterRequestToJSONTyped(value?: AuthhandlerRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'full_name': value['fullName'],
        'password': value['password'],
        'username': value['username'],
    };
}

