/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthhandlerRegisterErrorResponseData } from './AuthhandlerRegisterErrorResponseData';
import {
    AuthhandlerRegisterErrorResponseDataFromJSON,
    AuthhandlerRegisterErrorResponseDataFromJSONTyped,
    AuthhandlerRegisterErrorResponseDataToJSON,
    AuthhandlerRegisterErrorResponseDataToJSONTyped,
} from './AuthhandlerRegisterErrorResponseData';

/**
 * 
 * @export
 * @interface AuthhandlerRegisterResponse
 */
export interface AuthhandlerRegisterResponse {
    /**
     * 
     * @type {AuthhandlerRegisterErrorResponseData}
     * @memberof AuthhandlerRegisterResponse
     */
    data?: AuthhandlerRegisterErrorResponseData;
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerRegisterResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the AuthhandlerRegisterResponse interface.
 */
export function instanceOfAuthhandlerRegisterResponse(value: object): value is AuthhandlerRegisterResponse {
    return true;
}

export function AuthhandlerRegisterResponseFromJSON(json: any): AuthhandlerRegisterResponse {
    return AuthhandlerRegisterResponseFromJSONTyped(json, false);
}

export function AuthhandlerRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthhandlerRegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AuthhandlerRegisterErrorResponseDataFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function AuthhandlerRegisterResponseToJSON(json: any): AuthhandlerRegisterResponse {
      return AuthhandlerRegisterResponseToJSONTyped(json, false);
  }

  export function AuthhandlerRegisterResponseToJSONTyped(value?: AuthhandlerRegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AuthhandlerRegisterErrorResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

