"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthhandlerLoginResponse = instanceOfAuthhandlerLoginResponse;
exports.AuthhandlerLoginResponseFromJSON = AuthhandlerLoginResponseFromJSON;
exports.AuthhandlerLoginResponseFromJSONTyped = AuthhandlerLoginResponseFromJSONTyped;
exports.AuthhandlerLoginResponseToJSON = AuthhandlerLoginResponseToJSON;
exports.AuthhandlerLoginResponseToJSONTyped = AuthhandlerLoginResponseToJSONTyped;
var AuthhandlerLoginErrorResponseData_1 = require("./AuthhandlerLoginErrorResponseData");
/**
 * Check if a given object implements the AuthhandlerLoginResponse interface.
 */
function instanceOfAuthhandlerLoginResponse(value) {
    return true;
}
function AuthhandlerLoginResponseFromJSON(json) {
    return AuthhandlerLoginResponseFromJSONTyped(json, false);
}
function AuthhandlerLoginResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (0, AuthhandlerLoginErrorResponseData_1.AuthhandlerLoginErrorResponseDataFromJSON)(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function AuthhandlerLoginResponseToJSON(json) {
    return AuthhandlerLoginResponseToJSONTyped(json, false);
}
function AuthhandlerLoginResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'data': (0, AuthhandlerLoginErrorResponseData_1.AuthhandlerLoginErrorResponseDataToJSON)(value['data']),
        'status': value['status'],
    };
}
