/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLogin200Response
 */
export interface AuthLogin200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthLogin200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the AuthLogin200Response interface.
 */
export function instanceOfAuthLogin200Response(value: object): value is AuthLogin200Response {
    return true;
}

export function AuthLogin200ResponseFromJSON(json: any): AuthLogin200Response {
    return AuthLogin200ResponseFromJSONTyped(json, false);
}

export function AuthLogin200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogin200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

  export function AuthLogin200ResponseToJSON(json: any): AuthLogin200Response {
      return AuthLogin200ResponseToJSONTyped(json, false);
  }

  export function AuthLogin200ResponseToJSONTyped(value?: AuthLogin200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

