"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthhandlerRegisterRequest = instanceOfAuthhandlerRegisterRequest;
exports.AuthhandlerRegisterRequestFromJSON = AuthhandlerRegisterRequestFromJSON;
exports.AuthhandlerRegisterRequestFromJSONTyped = AuthhandlerRegisterRequestFromJSONTyped;
exports.AuthhandlerRegisterRequestToJSON = AuthhandlerRegisterRequestToJSON;
exports.AuthhandlerRegisterRequestToJSONTyped = AuthhandlerRegisterRequestToJSONTyped;
/**
 * Check if a given object implements the AuthhandlerRegisterRequest interface.
 */
function instanceOfAuthhandlerRegisterRequest(value) {
    return true;
}
function AuthhandlerRegisterRequestFromJSON(json) {
    return AuthhandlerRegisterRequestFromJSONTyped(json, false);
}
function AuthhandlerRegisterRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}
function AuthhandlerRegisterRequestToJSON(json) {
    return AuthhandlerRegisterRequestToJSONTyped(json, false);
}
function AuthhandlerRegisterRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'email': value['email'],
        'full_name': value['fullName'],
        'password': value['password'],
        'username': value['username'],
    };
}
