"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthhandlerLoginRequest = instanceOfAuthhandlerLoginRequest;
exports.AuthhandlerLoginRequestFromJSON = AuthhandlerLoginRequestFromJSON;
exports.AuthhandlerLoginRequestFromJSONTyped = AuthhandlerLoginRequestFromJSONTyped;
exports.AuthhandlerLoginRequestToJSON = AuthhandlerLoginRequestToJSON;
exports.AuthhandlerLoginRequestToJSONTyped = AuthhandlerLoginRequestToJSONTyped;
/**
 * Check if a given object implements the AuthhandlerLoginRequest interface.
 */
function instanceOfAuthhandlerLoginRequest(value) {
    return true;
}
function AuthhandlerLoginRequestFromJSON(json) {
    return AuthhandlerLoginRequestFromJSONTyped(json, false);
}
function AuthhandlerLoginRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}
function AuthhandlerLoginRequestToJSON(json) {
    return AuthhandlerLoginRequestToJSONTyped(json, false);
}
function AuthhandlerLoginRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'password': value['password'],
        'username': value['username'],
    };
}
