/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthhandlerRegisterErrorResponseData
 */
export interface AuthhandlerRegisterErrorResponseData {
    /**
     * 
     * @type {object}
     * @memberof AuthhandlerRegisterErrorResponseData
     */
    userId?: object;
}

/**
 * Check if a given object implements the AuthhandlerRegisterErrorResponseData interface.
 */
export function instanceOfAuthhandlerRegisterErrorResponseData(value: object): value is AuthhandlerRegisterErrorResponseData {
    return true;
}

export function AuthhandlerRegisterErrorResponseDataFromJSON(json: any): AuthhandlerRegisterErrorResponseData {
    return AuthhandlerRegisterErrorResponseDataFromJSONTyped(json, false);
}

export function AuthhandlerRegisterErrorResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthhandlerRegisterErrorResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

  export function AuthhandlerRegisterErrorResponseDataToJSON(json: any): AuthhandlerRegisterErrorResponseData {
      return AuthhandlerRegisterErrorResponseDataToJSONTyped(json, false);
  }

  export function AuthhandlerRegisterErrorResponseDataToJSONTyped(value?: AuthhandlerRegisterErrorResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

