"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthhandlerLoginErrorResponseData = instanceOfAuthhandlerLoginErrorResponseData;
exports.AuthhandlerLoginErrorResponseDataFromJSON = AuthhandlerLoginErrorResponseDataFromJSON;
exports.AuthhandlerLoginErrorResponseDataFromJSONTyped = AuthhandlerLoginErrorResponseDataFromJSONTyped;
exports.AuthhandlerLoginErrorResponseDataToJSON = AuthhandlerLoginErrorResponseDataToJSON;
exports.AuthhandlerLoginErrorResponseDataToJSONTyped = AuthhandlerLoginErrorResponseDataToJSONTyped;
/**
 * Check if a given object implements the AuthhandlerLoginErrorResponseData interface.
 */
function instanceOfAuthhandlerLoginErrorResponseData(value) {
    return true;
}
function AuthhandlerLoginErrorResponseDataFromJSON(json) {
    return AuthhandlerLoginErrorResponseDataFromJSONTyped(json, false);
}
function AuthhandlerLoginErrorResponseDataFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'token': json['token'] == null ? undefined : json['token'],
    };
}
function AuthhandlerLoginErrorResponseDataToJSON(json) {
    return AuthhandlerLoginErrorResponseDataToJSONTyped(json, false);
}
function AuthhandlerLoginErrorResponseDataToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'token': value['token'],
    };
}
