/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthhandlerLoginRequest
 */
export interface AuthhandlerLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerLoginRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthhandlerLoginRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the AuthhandlerLoginRequest interface.
 */
export function instanceOfAuthhandlerLoginRequest(value: object): value is AuthhandlerLoginRequest {
    return true;
}

export function AuthhandlerLoginRequestFromJSON(json: any): AuthhandlerLoginRequest {
    return AuthhandlerLoginRequestFromJSONTyped(json, false);
}

export function AuthhandlerLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthhandlerLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

  export function AuthhandlerLoginRequestToJSON(json: any): AuthhandlerLoginRequest {
      return AuthhandlerLoginRequestToJSONTyped(json, false);
  }

  export function AuthhandlerLoginRequestToJSONTyped(value?: AuthhandlerLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

