"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthhandlerRegisterErrorResponseData = instanceOfAuthhandlerRegisterErrorResponseData;
exports.AuthhandlerRegisterErrorResponseDataFromJSON = AuthhandlerRegisterErrorResponseDataFromJSON;
exports.AuthhandlerRegisterErrorResponseDataFromJSONTyped = AuthhandlerRegisterErrorResponseDataFromJSONTyped;
exports.AuthhandlerRegisterErrorResponseDataToJSON = AuthhandlerRegisterErrorResponseDataToJSON;
exports.AuthhandlerRegisterErrorResponseDataToJSONTyped = AuthhandlerRegisterErrorResponseDataToJSONTyped;
/**
 * Check if a given object implements the AuthhandlerRegisterErrorResponseData interface.
 */
function instanceOfAuthhandlerRegisterErrorResponseData(value) {
    return true;
}
function AuthhandlerRegisterErrorResponseDataFromJSON(json) {
    return AuthhandlerRegisterErrorResponseDataFromJSONTyped(json, false);
}
function AuthhandlerRegisterErrorResponseDataFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}
function AuthhandlerRegisterErrorResponseDataToJSON(json) {
    return AuthhandlerRegisterErrorResponseDataToJSONTyped(json, false);
}
function AuthhandlerRegisterErrorResponseDataToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'user_id': value['userId'],
    };
}
