"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAuthLoginPost200Response = instanceOfAuthLoginPost200Response;
exports.AuthLoginPost200ResponseFromJSON = AuthLoginPost200ResponseFromJSON;
exports.AuthLoginPost200ResponseFromJSONTyped = AuthLoginPost200ResponseFromJSONTyped;
exports.AuthLoginPost200ResponseToJSON = AuthLoginPost200ResponseToJSON;
exports.AuthLoginPost200ResponseToJSONTyped = AuthLoginPost200ResponseToJSONTyped;
/**
 * Check if a given object implements the AuthLoginPost200Response interface.
 */
function instanceOfAuthLoginPost200Response(value) {
    return true;
}
function AuthLoginPost200ResponseFromJSON(json) {
    return AuthLoginPost200ResponseFromJSONTyped(json, false);
}
function AuthLoginPost200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'token': json['token'] == null ? undefined : json['token'],
    };
}
function AuthLoginPost200ResponseToJSON(json) {
    return AuthLoginPost200ResponseToJSONTyped(json, false);
}
function AuthLoginPost200ResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'token': value['token'],
    };
}
