"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDomainSensorConfig = instanceOfDomainSensorConfig;
exports.DomainSensorConfigFromJSON = DomainSensorConfigFromJSON;
exports.DomainSensorConfigFromJSONTyped = DomainSensorConfigFromJSONTyped;
exports.DomainSensorConfigToJSON = DomainSensorConfigToJSON;
exports.DomainSensorConfigToJSONTyped = DomainSensorConfigToJSONTyped;
/**
 * Check if a given object implements the DomainSensorConfig interface.
 */
function instanceOfDomainSensorConfig(value) {
    return true;
}
function DomainSensorConfigFromJSON(json) {
    return DomainSensorConfigFromJSONTyped(json, false);
}
function DomainSensorConfigFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'sensorId': json['sensor_id'] == null ? undefined : json['sensor_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}
function DomainSensorConfigToJSON(json) {
    return DomainSensorConfigToJSONTyped(json, false);
}
function DomainSensorConfigToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'created_at': value['createdAt'],
        'id': value['id'],
        'key': value['key'],
        'sensor_id': value['sensorId'],
        'updated_at': value['updatedAt'],
        'value': value['value'],
    };
}
