/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainThermometerHistory
 */
export interface DomainThermometerHistory {
    /**
     * 
     * @type {object}
     * @memberof DomainThermometerHistory
     */
    id?: object;
    /**
     * 
     * @type {number}
     * @memberof DomainThermometerHistory
     */
    temperature?: number;
    /**
     * 
     * @type {object}
     * @memberof DomainThermometerHistory
     */
    thermometerId?: object;
    /**
     * 
     * @type {object}
     * @memberof DomainThermometerHistory
     */
    timestamp?: object;
}

/**
 * Check if a given object implements the DomainThermometerHistory interface.
 */
export function instanceOfDomainThermometerHistory(value: object): value is DomainThermometerHistory {
    return true;
}

export function DomainThermometerHistoryFromJSON(json: any): DomainThermometerHistory {
    return DomainThermometerHistoryFromJSONTyped(json, false);
}

export function DomainThermometerHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainThermometerHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'thermometerId': json['thermometer_id'] == null ? undefined : json['thermometer_id'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

  export function DomainThermometerHistoryToJSON(json: any): DomainThermometerHistory {
      return DomainThermometerHistoryToJSONTyped(json, false);
  }

  export function DomainThermometerHistoryToJSONTyped(value?: DomainThermometerHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'temperature': value['temperature'],
        'thermometer_id': value['thermometerId'],
        'timestamp': value['timestamp'],
    };
}

