/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainSensorConfig
 */
export interface DomainSensorConfig {
    /**
     * 
     * @type {object}
     * @memberof DomainSensorConfig
     */
    createdAt?: object;
    /**
     * 
     * @type {object}
     * @memberof DomainSensorConfig
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof DomainSensorConfig
     */
    key?: string;
    /**
     * 
     * @type {object}
     * @memberof DomainSensorConfig
     */
    sensorId?: object;
    /**
     * 
     * @type {object}
     * @memberof DomainSensorConfig
     */
    updatedAt?: object;
    /**
     * 
     * @type {Array<number>}
     * @memberof DomainSensorConfig
     */
    value?: Array<number>;
}

/**
 * Check if a given object implements the DomainSensorConfig interface.
 */
export function instanceOfDomainSensorConfig(value: object): value is DomainSensorConfig {
    return true;
}

export function DomainSensorConfigFromJSON(json: any): DomainSensorConfig {
    return DomainSensorConfigFromJSONTyped(json, false);
}

export function DomainSensorConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainSensorConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'sensorId': json['sensor_id'] == null ? undefined : json['sensor_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

  export function DomainSensorConfigToJSON(json: any): DomainSensorConfig {
      return DomainSensorConfigToJSONTyped(json, false);
  }

  export function DomainSensorConfigToJSONTyped(value?: DomainSensorConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'key': value['key'],
        'sensor_id': value['sensorId'],
        'updated_at': value['updatedAt'],
        'value': value['value'],
    };
}

