"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDomainThermometerHistory = instanceOfDomainThermometerHistory;
exports.DomainThermometerHistoryFromJSON = DomainThermometerHistoryFromJSON;
exports.DomainThermometerHistoryFromJSONTyped = DomainThermometerHistoryFromJSONTyped;
exports.DomainThermometerHistoryToJSON = DomainThermometerHistoryToJSON;
exports.DomainThermometerHistoryToJSONTyped = DomainThermometerHistoryToJSONTyped;
/**
 * Check if a given object implements the DomainThermometerHistory interface.
 */
function instanceOfDomainThermometerHistory(value) {
    return true;
}
function DomainThermometerHistoryFromJSON(json) {
    return DomainThermometerHistoryFromJSONTyped(json, false);
}
function DomainThermometerHistoryFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'thermometerId': json['thermometer_id'] == null ? undefined : json['thermometer_id'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}
function DomainThermometerHistoryToJSON(json) {
    return DomainThermometerHistoryToJSONTyped(json, false);
}
function DomainThermometerHistoryToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'temperature': value['temperature'],
        'thermometer_id': value['thermometerId'],
        'timestamp': value['timestamp'],
    };
}
