/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainSensorLog
 */
export interface DomainSensorLog {
    /**
     * 
     * @type {object}
     * @memberof DomainSensorLog
     */
    deviceId?: object;
    /**
     * 
     * @type {object}
     * @memberof DomainSensorLog
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof DomainSensorLog
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainSensorLog
     */
    sensorType?: string;
    /**
     * 
     * @type {object}
     * @memberof DomainSensorLog
     */
    timestamp?: object;
    /**
     * 
     * @type {number}
     * @memberof DomainSensorLog
     */
    value?: number;
}

/**
 * Check if a given object implements the DomainSensorLog interface.
 */
export function instanceOfDomainSensorLog(value: object): value is DomainSensorLog {
    return true;
}

export function DomainSensorLogFromJSON(json: any): DomainSensorLog {
    return DomainSensorLogFromJSONTyped(json, false);
}

export function DomainSensorLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainSensorLog {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['device_id'] == null ? undefined : json['device_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'sensorType': json['sensor_type'] == null ? undefined : json['sensor_type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

  export function DomainSensorLogToJSON(json: any): DomainSensorLog {
      return DomainSensorLogToJSONTyped(json, false);
  }

  export function DomainSensorLogToJSONTyped(value?: DomainSensorLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_id': value['deviceId'],
        'id': value['id'],
        'key': value['key'],
        'sensor_type': value['sensorType'],
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}

