"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDomainUserSetting = instanceOfDomainUserSetting;
exports.DomainUserSettingFromJSON = DomainUserSettingFromJSON;
exports.DomainUserSettingFromJSONTyped = DomainUserSettingFromJSONTyped;
exports.DomainUserSettingToJSON = DomainUserSettingToJSON;
exports.DomainUserSettingToJSONTyped = DomainUserSettingToJSONTyped;
/**
 * Check if a given object implements the DomainUserSetting interface.
 */
function instanceOfDomainUserSetting(value) {
    return true;
}
function DomainUserSettingFromJSON(json) {
    return DomainUserSettingFromJSONTyped(json, false);
}
function DomainUserSettingFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}
function DomainUserSettingToJSON(json) {
    return DomainUserSettingToJSONTyped(json, false);
}
function DomainUserSettingToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'created_at': value['createdAt'],
        'id': value['id'],
        'key': value['key'],
        'owner_id': value['ownerId'],
        'updated_at': value['updatedAt'],
        'value': value['value'],
    };
}
