/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainThermometerConfig
 */
export interface DomainThermometerConfig {
    /**
     * 
     * @type {string}
     * @memberof DomainThermometerConfig
     */
    connection?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainThermometerConfig
     */
    maxTemperature?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainThermometerConfig
     */
    minTemperature?: number;
}

/**
 * Check if a given object implements the DomainThermometerConfig interface.
 */
export function instanceOfDomainThermometerConfig(value: object): value is DomainThermometerConfig {
    return true;
}

export function DomainThermometerConfigFromJSON(json: any): DomainThermometerConfig {
    return DomainThermometerConfigFromJSONTyped(json, false);
}

export function DomainThermometerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainThermometerConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'connection': json['connection'] == null ? undefined : json['connection'],
        'maxTemperature': json['max_temperature'] == null ? undefined : json['max_temperature'],
        'minTemperature': json['min_temperature'] == null ? undefined : json['min_temperature'],
    };
}

  export function DomainThermometerConfigToJSON(json: any): DomainThermometerConfig {
      return DomainThermometerConfigToJSONTyped(json, false);
  }

  export function DomainThermometerConfigToJSONTyped(value?: DomainThermometerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection': value['connection'],
        'max_temperature': value['maxTemperature'],
        'min_temperature': value['minTemperature'],
    };
}

