"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfDomainSensorLog = instanceOfDomainSensorLog;
exports.DomainSensorLogFromJSON = DomainSensorLogFromJSON;
exports.DomainSensorLogFromJSONTyped = DomainSensorLogFromJSONTyped;
exports.DomainSensorLogToJSON = DomainSensorLogToJSON;
exports.DomainSensorLogToJSONTyped = DomainSensorLogToJSONTyped;
/**
 * Check if a given object implements the DomainSensorLog interface.
 */
function instanceOfDomainSensorLog(value) {
    return true;
}
function DomainSensorLogFromJSON(json) {
    return DomainSensorLogFromJSONTyped(json, false);
}
function DomainSensorLogFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'deviceId': json['device_id'] == null ? undefined : json['device_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'sensorType': json['sensor_type'] == null ? undefined : json['sensor_type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}
function DomainSensorLogToJSON(json) {
    return DomainSensorLogToJSONTyped(json, false);
}
function DomainSensorLogToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'device_id': value['deviceId'],
        'id': value['id'],
        'key': value['key'],
        'sensor_type': value['sensorType'],
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}
