/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthcheckGet200Response
 */
export interface HealthcheckGet200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthcheckGet200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the HealthcheckGet200Response interface.
 */
export function instanceOfHealthcheckGet200Response(value: object): value is HealthcheckGet200Response {
    return true;
}

export function HealthcheckGet200ResponseFromJSON(json: any): HealthcheckGet200Response {
    return HealthcheckGet200ResponseFromJSONTyped(json, false);
}

export function HealthcheckGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthcheckGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function HealthcheckGet200ResponseToJSON(json: any): HealthcheckGet200Response {
      return HealthcheckGet200ResponseToJSONTyped(json, false);
  }

  export function HealthcheckGet200ResponseToJSONTyped(value?: HealthcheckGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

