"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSensorhandlerListSensorLogsResponse = instanceOfSensorhandlerListSensorLogsResponse;
exports.SensorhandlerListSensorLogsResponseFromJSON = SensorhandlerListSensorLogsResponseFromJSON;
exports.SensorhandlerListSensorLogsResponseFromJSONTyped = SensorhandlerListSensorLogsResponseFromJSONTyped;
exports.SensorhandlerListSensorLogsResponseToJSON = SensorhandlerListSensorLogsResponseToJSON;
exports.SensorhandlerListSensorLogsResponseToJSONTyped = SensorhandlerListSensorLogsResponseToJSONTyped;
var DomainSensorLog_1 = require("./DomainSensorLog");
/**
 * Check if a given object implements the SensorhandlerListSensorLogsResponse interface.
 */
function instanceOfSensorhandlerListSensorLogsResponse(value) {
    return true;
}
function SensorhandlerListSensorLogsResponseFromJSON(json) {
    return SensorhandlerListSensorLogsResponseFromJSONTyped(json, false);
}
function SensorhandlerListSensorLogsResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (json['data'].map(DomainSensorLog_1.DomainSensorLogFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function SensorhandlerListSensorLogsResponseToJSON(json) {
    return SensorhandlerListSensorLogsResponseToJSONTyped(json, false);
}
function SensorhandlerListSensorLogsResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'data': value['data'] == null ? undefined : (value['data'].map(DomainSensorLog_1.DomainSensorLogToJSON)),
        'status': value['status'],
    };
}
