"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSensorhandlerCreateSensorResponse = instanceOfSensorhandlerCreateSensorResponse;
exports.SensorhandlerCreateSensorResponseFromJSON = SensorhandlerCreateSensorResponseFromJSON;
exports.SensorhandlerCreateSensorResponseFromJSONTyped = SensorhandlerCreateSensorResponseFromJSONTyped;
exports.SensorhandlerCreateSensorResponseToJSON = SensorhandlerCreateSensorResponseToJSON;
exports.SensorhandlerCreateSensorResponseToJSONTyped = SensorhandlerCreateSensorResponseToJSONTyped;
var DomainSensor_1 = require("./DomainSensor");
/**
 * Check if a given object implements the SensorhandlerCreateSensorResponse interface.
 */
function instanceOfSensorhandlerCreateSensorResponse(value) {
    return true;
}
function SensorhandlerCreateSensorResponseFromJSON(json) {
    return SensorhandlerCreateSensorResponseFromJSONTyped(json, false);
}
function SensorhandlerCreateSensorResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (0, DomainSensor_1.DomainSensorFromJSON)(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function SensorhandlerCreateSensorResponseToJSON(json) {
    return SensorhandlerCreateSensorResponseToJSONTyped(json, false);
}
function SensorhandlerCreateSensorResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'data': (0, DomainSensor_1.DomainSensorToJSON)(value['data']),
        'status': value['status'],
    };
}
