/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorhandlerCreateSensorRequest
 */
export interface SensorhandlerCreateSensorRequest {
    /**
     * 
     * @type {object}
     * @memberof SensorhandlerCreateSensorRequest
     */
    deviceId?: object;
    /**
     * 
     * @type {string}
     * @memberof SensorhandlerCreateSensorRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SensorhandlerCreateSensorRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the SensorhandlerCreateSensorRequest interface.
 */
export function instanceOfSensorhandlerCreateSensorRequest(value: object): value is SensorhandlerCreateSensorRequest {
    return true;
}

export function SensorhandlerCreateSensorRequestFromJSON(json: any): SensorhandlerCreateSensorRequest {
    return SensorhandlerCreateSensorRequestFromJSONTyped(json, false);
}

export function SensorhandlerCreateSensorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorhandlerCreateSensorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['device_id'] == null ? undefined : json['device_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

  export function SensorhandlerCreateSensorRequestToJSON(json: any): SensorhandlerCreateSensorRequest {
      return SensorhandlerCreateSensorRequestToJSONTyped(json, false);
  }

  export function SensorhandlerCreateSensorRequestToJSONTyped(value?: SensorhandlerCreateSensorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_id': value['deviceId'],
        'name': value['name'],
        'type': value['type'],
    };
}

