/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainSensor } from './DomainSensor';
import {
    DomainSensorFromJSON,
    DomainSensorFromJSONTyped,
    DomainSensorToJSON,
    DomainSensorToJSONTyped,
} from './DomainSensor';

/**
 * 
 * @export
 * @interface SensorhandlerCreateSensorResponse
 */
export interface SensorhandlerCreateSensorResponse {
    /**
     * 
     * @type {DomainSensor}
     * @memberof SensorhandlerCreateSensorResponse
     */
    data?: DomainSensor;
    /**
     * 
     * @type {string}
     * @memberof SensorhandlerCreateSensorResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the SensorhandlerCreateSensorResponse interface.
 */
export function instanceOfSensorhandlerCreateSensorResponse(value: object): value is SensorhandlerCreateSensorResponse {
    return true;
}

export function SensorhandlerCreateSensorResponseFromJSON(json: any): SensorhandlerCreateSensorResponse {
    return SensorhandlerCreateSensorResponseFromJSONTyped(json, false);
}

export function SensorhandlerCreateSensorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorhandlerCreateSensorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DomainSensorFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SensorhandlerCreateSensorResponseToJSON(json: any): SensorhandlerCreateSensorResponse {
      return SensorhandlerCreateSensorResponseToJSONTyped(json, false);
  }

  export function SensorhandlerCreateSensorResponseToJSONTyped(value?: SensorhandlerCreateSensorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DomainSensorToJSON(value['data']),
        'status': value['status'],
    };
}

