/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorhandlerCreateThermometerLogResponse
 */
export interface SensorhandlerCreateThermometerLogResponse {
    /**
     * 
     * @type {string}
     * @memberof SensorhandlerCreateThermometerLogResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SensorhandlerCreateThermometerLogResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the SensorhandlerCreateThermometerLogResponse interface.
 */
export function instanceOfSensorhandlerCreateThermometerLogResponse(value: object): value is SensorhandlerCreateThermometerLogResponse {
    return true;
}

export function SensorhandlerCreateThermometerLogResponseFromJSON(json: any): SensorhandlerCreateThermometerLogResponse {
    return SensorhandlerCreateThermometerLogResponseFromJSONTyped(json, false);
}

export function SensorhandlerCreateThermometerLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorhandlerCreateThermometerLogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SensorhandlerCreateThermometerLogResponseToJSON(json: any): SensorhandlerCreateThermometerLogResponse {
      return SensorhandlerCreateThermometerLogResponseToJSONTyped(json, false);
  }

  export function SensorhandlerCreateThermometerLogResponseToJSONTyped(value?: SensorhandlerCreateThermometerLogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

