"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSensorhandlerCreateThermometerLogResponse = instanceOfSensorhandlerCreateThermometerLogResponse;
exports.SensorhandlerCreateThermometerLogResponseFromJSON = SensorhandlerCreateThermometerLogResponseFromJSON;
exports.SensorhandlerCreateThermometerLogResponseFromJSONTyped = SensorhandlerCreateThermometerLogResponseFromJSONTyped;
exports.SensorhandlerCreateThermometerLogResponseToJSON = SensorhandlerCreateThermometerLogResponseToJSON;
exports.SensorhandlerCreateThermometerLogResponseToJSONTyped = SensorhandlerCreateThermometerLogResponseToJSONTyped;
/**
 * Check if a given object implements the SensorhandlerCreateThermometerLogResponse interface.
 */
function instanceOfSensorhandlerCreateThermometerLogResponse(value) {
    return true;
}
function SensorhandlerCreateThermometerLogResponseFromJSON(json) {
    return SensorhandlerCreateThermometerLogResponseFromJSONTyped(json, false);
}
function SensorhandlerCreateThermometerLogResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function SensorhandlerCreateThermometerLogResponseToJSON(json) {
    return SensorhandlerCreateThermometerLogResponseToJSONTyped(json, false);
}
function SensorhandlerCreateThermometerLogResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
        'status': value['status'],
    };
}
