"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SensorLogSensorTypeEnum = void 0;
exports.instanceOfSensorLog = instanceOfSensorLog;
exports.SensorLogFromJSON = SensorLogFromJSON;
exports.SensorLogFromJSONTyped = SensorLogFromJSONTyped;
exports.SensorLogToJSON = SensorLogToJSON;
exports.SensorLogToJSONTyped = SensorLogToJSONTyped;
/**
 * @export
 */
exports.SensorLogSensorTypeEnum = {
    Temperature: 'temperature'
};
/**
 * Check if a given object implements the SensorLog interface.
 */
function instanceOfSensorLog(value) {
    return true;
}
function SensorLogFromJSON(json) {
    return SensorLogFromJSONTyped(json, false);
}
function SensorLogFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'deviceId': json['device_id'] == null ? undefined : json['device_id'],
        'sensorType': json['sensor_type'] == null ? undefined : json['sensor_type'],
        'value': json['value'] == null ? undefined : json['value'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}
function SensorLogToJSON(json) {
    return SensorLogToJSONTyped(json, false);
}
function SensorLogToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {};
}
