/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulatorhandlerUpdateThermometerConfigResponse
 */
export interface SimulatorhandlerUpdateThermometerConfigResponse {
    /**
     * 
     * @type {string}
     * @memberof SimulatorhandlerUpdateThermometerConfigResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatorhandlerUpdateThermometerConfigResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the SimulatorhandlerUpdateThermometerConfigResponse interface.
 */
export function instanceOfSimulatorhandlerUpdateThermometerConfigResponse(value: object): value is SimulatorhandlerUpdateThermometerConfigResponse {
    return true;
}

export function SimulatorhandlerUpdateThermometerConfigResponseFromJSON(json: any): SimulatorhandlerUpdateThermometerConfigResponse {
    return SimulatorhandlerUpdateThermometerConfigResponseFromJSONTyped(json, false);
}

export function SimulatorhandlerUpdateThermometerConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorhandlerUpdateThermometerConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorhandlerUpdateThermometerConfigResponseToJSON(json: any): SimulatorhandlerUpdateThermometerConfigResponse {
      return SimulatorhandlerUpdateThermometerConfigResponseToJSONTyped(json, false);
  }

  export function SimulatorhandlerUpdateThermometerConfigResponseToJSONTyped(value?: SimulatorhandlerUpdateThermometerConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

