/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainThermometerHistory } from './DomainThermometerHistory';
import {
    DomainThermometerHistoryFromJSON,
    DomainThermometerHistoryFromJSONTyped,
    DomainThermometerHistoryToJSON,
    DomainThermometerHistoryToJSONTyped,
} from './DomainThermometerHistory';

/**
 * 
 * @export
 * @interface SimulatorhandlerGetTMHistoryResponse
 */
export interface SimulatorhandlerGetTMHistoryResponse {
    /**
     * 
     * @type {Array<DomainThermometerHistory>}
     * @memberof SimulatorhandlerGetTMHistoryResponse
     */
    data?: Array<DomainThermometerHistory>;
    /**
     * 
     * @type {number}
     * @memberof SimulatorhandlerGetTMHistoryResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SimulatorhandlerGetTMHistoryResponse interface.
 */
export function instanceOfSimulatorhandlerGetTMHistoryResponse(value: object): value is SimulatorhandlerGetTMHistoryResponse {
    return true;
}

export function SimulatorhandlerGetTMHistoryResponseFromJSON(json: any): SimulatorhandlerGetTMHistoryResponse {
    return SimulatorhandlerGetTMHistoryResponseFromJSONTyped(json, false);
}

export function SimulatorhandlerGetTMHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorhandlerGetTMHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DomainThermometerHistoryFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorhandlerGetTMHistoryResponseToJSON(json: any): SimulatorhandlerGetTMHistoryResponse {
      return SimulatorhandlerGetTMHistoryResponseToJSONTyped(json, false);
  }

  export function SimulatorhandlerGetTMHistoryResponseToJSONTyped(value?: SimulatorhandlerGetTMHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DomainThermometerHistoryToJSON)),
        'status': value['status'],
    };
}

