"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSimulatorhandlerListThermometersResponse = instanceOfSimulatorhandlerListThermometersResponse;
exports.SimulatorhandlerListThermometersResponseFromJSON = SimulatorhandlerListThermometersResponseFromJSON;
exports.SimulatorhandlerListThermometersResponseFromJSONTyped = SimulatorhandlerListThermometersResponseFromJSONTyped;
exports.SimulatorhandlerListThermometersResponseToJSON = SimulatorhandlerListThermometersResponseToJSON;
exports.SimulatorhandlerListThermometersResponseToJSONTyped = SimulatorhandlerListThermometersResponseToJSONTyped;
var DomainThermometer_1 = require("./DomainThermometer");
/**
 * Check if a given object implements the SimulatorhandlerListThermometersResponse interface.
 */
function instanceOfSimulatorhandlerListThermometersResponse(value) {
    return true;
}
function SimulatorhandlerListThermometersResponseFromJSON(json) {
    return SimulatorhandlerListThermometersResponseFromJSONTyped(json, false);
}
function SimulatorhandlerListThermometersResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (json['data'].map(DomainThermometer_1.DomainThermometerFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function SimulatorhandlerListThermometersResponseToJSON(json) {
    return SimulatorhandlerListThermometersResponseToJSONTyped(json, false);
}
function SimulatorhandlerListThermometersResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'data': value['data'] == null ? undefined : (value['data'].map(DomainThermometer_1.DomainThermometerToJSON)),
        'status': value['status'],
    };
}
