/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulatorhandlerStartEngineResponse
 */
export interface SimulatorhandlerStartEngineResponse {
    /**
     * 
     * @type {string}
     * @memberof SimulatorhandlerStartEngineResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatorhandlerStartEngineResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the SimulatorhandlerStartEngineResponse interface.
 */
export function instanceOfSimulatorhandlerStartEngineResponse(value: object): value is SimulatorhandlerStartEngineResponse {
    return true;
}

export function SimulatorhandlerStartEngineResponseFromJSON(json: any): SimulatorhandlerStartEngineResponse {
    return SimulatorhandlerStartEngineResponseFromJSONTyped(json, false);
}

export function SimulatorhandlerStartEngineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorhandlerStartEngineResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorhandlerStartEngineResponseToJSON(json: any): SimulatorhandlerStartEngineResponse {
      return SimulatorhandlerStartEngineResponseToJSONTyped(json, false);
  }

  export function SimulatorhandlerStartEngineResponseToJSONTyped(value?: SimulatorhandlerStartEngineResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

