"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSimulatorhandlerCreateThermometerRequest = instanceOfSimulatorhandlerCreateThermometerRequest;
exports.SimulatorhandlerCreateThermometerRequestFromJSON = SimulatorhandlerCreateThermometerRequestFromJSON;
exports.SimulatorhandlerCreateThermometerRequestFromJSONTyped = SimulatorhandlerCreateThermometerRequestFromJSONTyped;
exports.SimulatorhandlerCreateThermometerRequestToJSON = SimulatorhandlerCreateThermometerRequestToJSON;
exports.SimulatorhandlerCreateThermometerRequestToJSONTyped = SimulatorhandlerCreateThermometerRequestToJSONTyped;
var DomainThermometerConfig_1 = require("./DomainThermometerConfig");
/**
 * Check if a given object implements the SimulatorhandlerCreateThermometerRequest interface.
 */
function instanceOfSimulatorhandlerCreateThermometerRequest(value) {
    return true;
}
function SimulatorhandlerCreateThermometerRequestFromJSON(json) {
    return SimulatorhandlerCreateThermometerRequestFromJSONTyped(json, false);
}
function SimulatorhandlerCreateThermometerRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'config': json['config'] == null ? undefined : (0, DomainThermometerConfig_1.DomainThermometerConfigFromJSON)(json['config']),
    };
}
function SimulatorhandlerCreateThermometerRequestToJSON(json) {
    return SimulatorhandlerCreateThermometerRequestToJSONTyped(json, false);
}
function SimulatorhandlerCreateThermometerRequestToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'config': (0, DomainThermometerConfig_1.DomainThermometerConfigToJSON)(value['config']),
    };
}
