"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSimulatorhandlerUpdateThermometerConfigResponse = instanceOfSimulatorhandlerUpdateThermometerConfigResponse;
exports.SimulatorhandlerUpdateThermometerConfigResponseFromJSON = SimulatorhandlerUpdateThermometerConfigResponseFromJSON;
exports.SimulatorhandlerUpdateThermometerConfigResponseFromJSONTyped = SimulatorhandlerUpdateThermometerConfigResponseFromJSONTyped;
exports.SimulatorhandlerUpdateThermometerConfigResponseToJSON = SimulatorhandlerUpdateThermometerConfigResponseToJSON;
exports.SimulatorhandlerUpdateThermometerConfigResponseToJSONTyped = SimulatorhandlerUpdateThermometerConfigResponseToJSONTyped;
/**
 * Check if a given object implements the SimulatorhandlerUpdateThermometerConfigResponse interface.
 */
function instanceOfSimulatorhandlerUpdateThermometerConfigResponse(value) {
    return true;
}
function SimulatorhandlerUpdateThermometerConfigResponseFromJSON(json) {
    return SimulatorhandlerUpdateThermometerConfigResponseFromJSONTyped(json, false);
}
function SimulatorhandlerUpdateThermometerConfigResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function SimulatorhandlerUpdateThermometerConfigResponseToJSON(json) {
    return SimulatorhandlerUpdateThermometerConfigResponseToJSONTyped(json, false);
}
function SimulatorhandlerUpdateThermometerConfigResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
        'status': value['status'],
    };
}
