"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSimulatorhandlerCreateThermometerResponse = instanceOfSimulatorhandlerCreateThermometerResponse;
exports.SimulatorhandlerCreateThermometerResponseFromJSON = SimulatorhandlerCreateThermometerResponseFromJSON;
exports.SimulatorhandlerCreateThermometerResponseFromJSONTyped = SimulatorhandlerCreateThermometerResponseFromJSONTyped;
exports.SimulatorhandlerCreateThermometerResponseToJSON = SimulatorhandlerCreateThermometerResponseToJSON;
exports.SimulatorhandlerCreateThermometerResponseToJSONTyped = SimulatorhandlerCreateThermometerResponseToJSONTyped;
var DomainThermometer_1 = require("./DomainThermometer");
/**
 * Check if a given object implements the SimulatorhandlerCreateThermometerResponse interface.
 */
function instanceOfSimulatorhandlerCreateThermometerResponse(value) {
    return true;
}
function SimulatorhandlerCreateThermometerResponseFromJSON(json) {
    return SimulatorhandlerCreateThermometerResponseFromJSONTyped(json, false);
}
function SimulatorhandlerCreateThermometerResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (0, DomainThermometer_1.DomainThermometerFromJSON)(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function SimulatorhandlerCreateThermometerResponseToJSON(json) {
    return SimulatorhandlerCreateThermometerResponseToJSONTyped(json, false);
}
function SimulatorhandlerCreateThermometerResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'data': (0, DomainThermometer_1.DomainThermometerToJSON)(value['data']),
        'status': value['status'],
    };
}
