"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSimulatorhandlerEngineSwitchResponse = instanceOfSimulatorhandlerEngineSwitchResponse;
exports.SimulatorhandlerEngineSwitchResponseFromJSON = SimulatorhandlerEngineSwitchResponseFromJSON;
exports.SimulatorhandlerEngineSwitchResponseFromJSONTyped = SimulatorhandlerEngineSwitchResponseFromJSONTyped;
exports.SimulatorhandlerEngineSwitchResponseToJSON = SimulatorhandlerEngineSwitchResponseToJSON;
exports.SimulatorhandlerEngineSwitchResponseToJSONTyped = SimulatorhandlerEngineSwitchResponseToJSONTyped;
/**
 * Check if a given object implements the SimulatorhandlerEngineSwitchResponse interface.
 */
function instanceOfSimulatorhandlerEngineSwitchResponse(value) {
    return true;
}
function SimulatorhandlerEngineSwitchResponseFromJSON(json) {
    return SimulatorhandlerEngineSwitchResponseFromJSONTyped(json, false);
}
function SimulatorhandlerEngineSwitchResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function SimulatorhandlerEngineSwitchResponseToJSON(json) {
    return SimulatorhandlerEngineSwitchResponseToJSONTyped(json, false);
}
function SimulatorhandlerEngineSwitchResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
        'status': value['status'],
    };
}
