/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulatorhandlerEngineSwitchResponse
 */
export interface SimulatorhandlerEngineSwitchResponse {
    /**
     * 
     * @type {string}
     * @memberof SimulatorhandlerEngineSwitchResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof SimulatorhandlerEngineSwitchResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SimulatorhandlerEngineSwitchResponse interface.
 */
export function instanceOfSimulatorhandlerEngineSwitchResponse(value: object): value is SimulatorhandlerEngineSwitchResponse {
    return true;
}

export function SimulatorhandlerEngineSwitchResponseFromJSON(json: any): SimulatorhandlerEngineSwitchResponse {
    return SimulatorhandlerEngineSwitchResponseFromJSONTyped(json, false);
}

export function SimulatorhandlerEngineSwitchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorhandlerEngineSwitchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorhandlerEngineSwitchResponseToJSON(json: any): SimulatorhandlerEngineSwitchResponse {
      return SimulatorhandlerEngineSwitchResponseToJSONTyped(json, false);
  }

  export function SimulatorhandlerEngineSwitchResponseToJSONTyped(value?: SimulatorhandlerEngineSwitchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

