/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainThermometer } from './DomainThermometer';
import {
    DomainThermometerFromJSON,
    DomainThermometerFromJSONTyped,
    DomainThermometerToJSON,
    DomainThermometerToJSONTyped,
} from './DomainThermometer';

/**
 * 
 * @export
 * @interface SimulatorhandlerCreateThermometerResponse
 */
export interface SimulatorhandlerCreateThermometerResponse {
    /**
     * 
     * @type {DomainThermometer}
     * @memberof SimulatorhandlerCreateThermometerResponse
     */
    data?: DomainThermometer;
    /**
     * 
     * @type {number}
     * @memberof SimulatorhandlerCreateThermometerResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SimulatorhandlerCreateThermometerResponse interface.
 */
export function instanceOfSimulatorhandlerCreateThermometerResponse(value: object): value is SimulatorhandlerCreateThermometerResponse {
    return true;
}

export function SimulatorhandlerCreateThermometerResponseFromJSON(json: any): SimulatorhandlerCreateThermometerResponse {
    return SimulatorhandlerCreateThermometerResponseFromJSONTyped(json, false);
}

export function SimulatorhandlerCreateThermometerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorhandlerCreateThermometerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DomainThermometerFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorhandlerCreateThermometerResponseToJSON(json: any): SimulatorhandlerCreateThermometerResponse {
      return SimulatorhandlerCreateThermometerResponseToJSONTyped(json, false);
  }

  export function SimulatorhandlerCreateThermometerResponseToJSONTyped(value?: SimulatorhandlerCreateThermometerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DomainThermometerToJSON(value['data']),
        'status': value['status'],
    };
}

