/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainThermometer } from './DomainThermometer';
import {
    DomainThermometerFromJSON,
    DomainThermometerFromJSONTyped,
    DomainThermometerToJSON,
    DomainThermometerToJSONTyped,
} from './DomainThermometer';

/**
 * 
 * @export
 * @interface SimulatorhandlerListThermometersResponse
 */
export interface SimulatorhandlerListThermometersResponse {
    /**
     * 
     * @type {Array<DomainThermometer>}
     * @memberof SimulatorhandlerListThermometersResponse
     */
    data?: Array<DomainThermometer>;
    /**
     * 
     * @type {number}
     * @memberof SimulatorhandlerListThermometersResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SimulatorhandlerListThermometersResponse interface.
 */
export function instanceOfSimulatorhandlerListThermometersResponse(value: object): value is SimulatorhandlerListThermometersResponse {
    return true;
}

export function SimulatorhandlerListThermometersResponseFromJSON(json: any): SimulatorhandlerListThermometersResponse {
    return SimulatorhandlerListThermometersResponseFromJSONTyped(json, false);
}

export function SimulatorhandlerListThermometersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorhandlerListThermometersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DomainThermometerFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorhandlerListThermometersResponseToJSON(json: any): SimulatorhandlerListThermometersResponse {
      return SimulatorhandlerListThermometersResponseToJSONTyped(json, false);
  }

  export function SimulatorhandlerListThermometersResponseToJSONTyped(value?: SimulatorhandlerListThermometersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DomainThermometerToJSON)),
        'status': value['status'],
    };
}

