/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThermometerConfig
 */
export interface ThermometerConfig {
    /**
     * The connection type of the thermometer
     * @type {string}
     * @memberof ThermometerConfig
     */
    connection?: string;
    /**
     * The minimum temperature of the thermometer
     * @type {number}
     * @memberof ThermometerConfig
     */
    minTemperature?: number;
    /**
     * The maximum temperature of the thermometer
     * @type {number}
     * @memberof ThermometerConfig
     */
    maxTemperature?: number;
}

/**
 * Check if a given object implements the ThermometerConfig interface.
 */
export function instanceOfThermometerConfig(value: object): value is ThermometerConfig {
    return true;
}

export function ThermometerConfigFromJSON(json: any): ThermometerConfig {
    return ThermometerConfigFromJSONTyped(json, false);
}

export function ThermometerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThermometerConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'connection': json['connection'] == null ? undefined : json['connection'],
        'minTemperature': json['min_temperature'] == null ? undefined : json['min_temperature'],
        'maxTemperature': json['max_temperature'] == null ? undefined : json['max_temperature'],
    };
}

  export function ThermometerConfigToJSON(json: any): ThermometerConfig {
      return ThermometerConfigToJSONTyped(json, false);
  }

  export function ThermometerConfigToJSONTyped(value?: ThermometerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection': value['connection'],
        'min_temperature': value['minTemperature'],
        'max_temperature': value['maxTemperature'],
    };
}

