"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserSetting = instanceOfUserSetting;
exports.UserSettingFromJSON = UserSettingFromJSON;
exports.UserSettingFromJSONTyped = UserSettingFromJSONTyped;
exports.UserSettingToJSON = UserSettingToJSON;
exports.UserSettingToJSONTyped = UserSettingToJSONTyped;
/**
 * Check if a given object implements the UserSetting interface.
 */
function instanceOfUserSetting(value) {
    return true;
}
function UserSettingFromJSON(json) {
    return UserSettingFromJSONTyped(json, false);
}
function UserSettingFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}
function UserSettingToJSON(json) {
    return UserSettingToJSONTyped(json, false);
}
function UserSettingToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'key': value['key'],
        'value': value['value'],
    };
}
