/* tslint:disable */
/* eslint-disable */
/**
 * IOT DASHBOARD SENSOR MONITORING API
 * API FOR IOT DASHBOARD SENSOR MONITORING
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSetting
 */
export interface UserSetting {
    /**
     * The ID of the user setting
     * @type {string}
     * @memberof UserSetting
     */
    readonly id?: string;
    /**
     * The key of the user setting
     * @type {string}
     * @memberof UserSetting
     */
    key?: string;
    /**
     * The value of the user setting
     * @type {string}
     * @memberof UserSetting
     */
    value?: string;
    /**
     * The creation date of the user setting
     * @type {Date}
     * @memberof UserSetting
     */
    readonly createdAt?: Date;
    /**
     * The update date of the user setting
     * @type {Date}
     * @memberof UserSetting
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the UserSetting interface.
 */
export function instanceOfUserSetting(value: object): value is UserSetting {
    return true;
}

export function UserSettingFromJSON(json: any): UserSetting {
    return UserSettingFromJSONTyped(json, false);
}

export function UserSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

  export function UserSettingToJSON(json: any): UserSetting {
      return UserSettingToJSONTyped(json, false);
  }

  export function UserSettingToJSONTyped(value?: Omit<UserSetting, 'id'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

