"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUserhandlerGetMeResponse = instanceOfUserhandlerGetMeResponse;
exports.UserhandlerGetMeResponseFromJSON = UserhandlerGetMeResponseFromJSON;
exports.UserhandlerGetMeResponseFromJSONTyped = UserhandlerGetMeResponseFromJSONTyped;
exports.UserhandlerGetMeResponseToJSON = UserhandlerGetMeResponseToJSON;
exports.UserhandlerGetMeResponseToJSONTyped = UserhandlerGetMeResponseToJSONTyped;
var DomainUser_1 = require("./DomainUser");
/**
 * Check if a given object implements the UserhandlerGetMeResponse interface.
 */
function instanceOfUserhandlerGetMeResponse(value) {
    return true;
}
function UserhandlerGetMeResponseFromJSON(json) {
    return UserhandlerGetMeResponseFromJSONTyped(json, false);
}
function UserhandlerGetMeResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': json['data'] == null ? undefined : (0, DomainUser_1.DomainUserFromJSON)(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}
function UserhandlerGetMeResponseToJSON(json) {
    return UserhandlerGetMeResponseToJSONTyped(json, false);
}
function UserhandlerGetMeResponseToJSONTyped(value, ignoreDiscriminator) {
    if (ignoreDiscriminator === void 0) { ignoreDiscriminator = false; }
    if (value == null) {
        return value;
    }
    return {
        'data': (0, DomainUser_1.DomainUserToJSON)(value['data']),
        'status': value['status'],
    };
}
