/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainUserSetting } from './DomainUserSetting';
import {
    DomainUserSettingFromJSON,
    DomainUserSettingFromJSONTyped,
    DomainUserSettingToJSON,
    DomainUserSettingToJSONTyped,
} from './DomainUserSetting';

/**
 * 
 * @export
 * @interface UserhandlerGetMeSettingsResponse
 */
export interface UserhandlerGetMeSettingsResponse {
    /**
     * 
     * @type {Array<DomainUserSetting>}
     * @memberof UserhandlerGetMeSettingsResponse
     */
    data?: Array<DomainUserSetting>;
    /**
     * 
     * @type {string}
     * @memberof UserhandlerGetMeSettingsResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the UserhandlerGetMeSettingsResponse interface.
 */
export function instanceOfUserhandlerGetMeSettingsResponse(value: object): value is UserhandlerGetMeSettingsResponse {
    return true;
}

export function UserhandlerGetMeSettingsResponseFromJSON(json: any): UserhandlerGetMeSettingsResponse {
    return UserhandlerGetMeSettingsResponseFromJSONTyped(json, false);
}

export function UserhandlerGetMeSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserhandlerGetMeSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DomainUserSettingFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function UserhandlerGetMeSettingsResponseToJSON(json: any): UserhandlerGetMeSettingsResponse {
      return UserhandlerGetMeSettingsResponseToJSONTyped(json, false);
  }

  export function UserhandlerGetMeSettingsResponseToJSONTyped(value?: UserhandlerGetMeSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DomainUserSettingToJSON)),
        'status': value['status'],
    };
}

