/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRegisterErrorResponseData
 */
export interface AuthRegisterErrorResponseData {
    /**
     * 
     * @type {object}
     * @memberof AuthRegisterErrorResponseData
     */
    userId?: object;
}

/**
 * Check if a given object implements the AuthRegisterErrorResponseData interface.
 */
export function instanceOfAuthRegisterErrorResponseData(value: object): value is AuthRegisterErrorResponseData {
    return true;
}

export function AuthRegisterErrorResponseDataFromJSON(json: any): AuthRegisterErrorResponseData {
    return AuthRegisterErrorResponseDataFromJSONTyped(json, false);
}

export function AuthRegisterErrorResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterErrorResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

  export function AuthRegisterErrorResponseDataToJSON(json: any): AuthRegisterErrorResponseData {
      return AuthRegisterErrorResponseDataToJSONTyped(json, false);
  }

  export function AuthRegisterErrorResponseDataToJSONTyped(value?: AuthRegisterErrorResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

