/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginRequest
 */
export interface AuthLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the AuthLoginRequest interface.
 */
export function instanceOfAuthLoginRequest(value: object): value is AuthLoginRequest {
    return true;
}

export function AuthLoginRequestFromJSON(json: any): AuthLoginRequest {
    return AuthLoginRequestFromJSONTyped(json, false);
}

export function AuthLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

  export function AuthLoginRequestToJSON(json: any): AuthLoginRequest {
      return AuthLoginRequestToJSONTyped(json, false);
  }

  export function AuthLoginRequestToJSONTyped(value?: AuthLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

