/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRegisterRequest
 */
export interface AuthRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the AuthRegisterRequest interface.
 */
export function instanceOfAuthRegisterRequest(value: object): value is AuthRegisterRequest {
    return true;
}

export function AuthRegisterRequestFromJSON(json: any): AuthRegisterRequest {
    return AuthRegisterRequestFromJSONTyped(json, false);
}

export function AuthRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

  export function AuthRegisterRequestToJSON(json: any): AuthRegisterRequest {
      return AuthRegisterRequestToJSONTyped(json, false);
  }

  export function AuthRegisterRequestToJSONTyped(value?: AuthRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'full_name': value['fullName'],
        'password': value['password'],
        'username': value['username'],
    };
}

