/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRegisterErrorResponseData } from './AuthRegisterErrorResponseData';
import {
    AuthRegisterErrorResponseDataFromJSON,
    AuthRegisterErrorResponseDataFromJSONTyped,
    AuthRegisterErrorResponseDataToJSON,
    AuthRegisterErrorResponseDataToJSONTyped,
} from './AuthRegisterErrorResponseData';

/**
 * 
 * @export
 * @interface AuthRegisterResponse
 */
export interface AuthRegisterResponse {
    /**
     * 
     * @type {AuthRegisterErrorResponseData}
     * @memberof AuthRegisterResponse
     */
    data?: AuthRegisterErrorResponseData;
    /**
     * 
     * @type {number}
     * @memberof AuthRegisterResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the AuthRegisterResponse interface.
 */
export function instanceOfAuthRegisterResponse(value: object): value is AuthRegisterResponse {
    return true;
}

export function AuthRegisterResponseFromJSON(json: any): AuthRegisterResponse {
    return AuthRegisterResponseFromJSONTyped(json, false);
}

export function AuthRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AuthRegisterErrorResponseDataFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function AuthRegisterResponseToJSON(json: any): AuthRegisterResponse {
      return AuthRegisterResponseToJSONTyped(json, false);
  }

  export function AuthRegisterResponseToJSONTyped(value?: AuthRegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AuthRegisterErrorResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

