/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthLoginErrorResponseData } from './AuthLoginErrorResponseData';
import {
    AuthLoginErrorResponseDataFromJSON,
    AuthLoginErrorResponseDataFromJSONTyped,
    AuthLoginErrorResponseDataToJSON,
    AuthLoginErrorResponseDataToJSONTyped,
} from './AuthLoginErrorResponseData';

/**
 * 
 * @export
 * @interface AuthLoginResponse
 */
export interface AuthLoginResponse {
    /**
     * 
     * @type {AuthLoginErrorResponseData}
     * @memberof AuthLoginResponse
     */
    data?: AuthLoginErrorResponseData;
    /**
     * 
     * @type {number}
     * @memberof AuthLoginResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the AuthLoginResponse interface.
 */
export function instanceOfAuthLoginResponse(value: object): value is AuthLoginResponse {
    return true;
}

export function AuthLoginResponseFromJSON(json: any): AuthLoginResponse {
    return AuthLoginResponseFromJSONTyped(json, false);
}

export function AuthLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AuthLoginErrorResponseDataFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function AuthLoginResponseToJSON(json: any): AuthLoginResponse {
      return AuthLoginResponseToJSONTyped(json, false);
  }

  export function AuthLoginResponseToJSONTyped(value?: AuthLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AuthLoginErrorResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

