/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityUserSetting
 */
export interface EntityUserSetting {
    /**
     * 
     * @type {object}
     * @memberof EntityUserSetting
     */
    createdAt?: object;
    /**
     * 
     * @type {object}
     * @memberof EntityUserSetting
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof EntityUserSetting
     */
    key?: string;
    /**
     * 
     * @type {object}
     * @memberof EntityUserSetting
     */
    ownerId?: object;
    /**
     * 
     * @type {object}
     * @memberof EntityUserSetting
     */
    updatedAt?: object;
    /**
     * 
     * @type {Array<number>}
     * @memberof EntityUserSetting
     */
    value?: Array<number>;
}

/**
 * Check if a given object implements the EntityUserSetting interface.
 */
export function instanceOfEntityUserSetting(value: object): value is EntityUserSetting {
    return true;
}

export function EntityUserSettingFromJSON(json: any): EntityUserSetting {
    return EntityUserSettingFromJSONTyped(json, false);
}

export function EntityUserSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityUserSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

  export function EntityUserSettingToJSON(json: any): EntityUserSetting {
      return EntityUserSettingToJSONTyped(json, false);
  }

  export function EntityUserSettingToJSONTyped(value?: EntityUserSetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'key': value['key'],
        'owner_id': value['ownerId'],
        'updated_at': value['updatedAt'],
        'value': value['value'],
    };
}

