/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityThermometerConfig } from './EntityThermometerConfig';
import {
    EntityThermometerConfigFromJSON,
    EntityThermometerConfigFromJSONTyped,
    EntityThermometerConfigToJSON,
    EntityThermometerConfigToJSONTyped,
} from './EntityThermometerConfig';

/**
 * 
 * @export
 * @interface EntityThermometer
 */
export interface EntityThermometer {
    /**
     * 
     * @type {EntityThermometerConfig}
     * @memberof EntityThermometer
     */
    config?: EntityThermometerConfig;
    /**
     * 
     * @type {boolean}
     * @memberof EntityThermometer
     */
    connected?: boolean;
    /**
     * 
     * @type {object}
     * @memberof EntityThermometer
     */
    createdAt?: object;
    /**
     * 
     * @type {object}
     * @memberof EntityThermometer
     */
    id?: object;
    /**
     * 
     * @type {string}
     * @memberof EntityThermometer
     */
    ipAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityThermometer
     */
    isActive?: boolean;
    /**
     * 
     * @type {object}
     * @memberof EntityThermometer
     */
    ownerId?: object;
    /**
     * 
     * @type {number}
     * @memberof EntityThermometer
     */
    temperature?: number;
    /**
     * 
     * @type {object}
     * @memberof EntityThermometer
     */
    updatedAt?: object;
}

/**
 * Check if a given object implements the EntityThermometer interface.
 */
export function instanceOfEntityThermometer(value: object): value is EntityThermometer {
    return true;
}

export function EntityThermometerFromJSON(json: any): EntityThermometer {
    return EntityThermometerFromJSONTyped(json, false);
}

export function EntityThermometerFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityThermometer {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : EntityThermometerConfigFromJSON(json['config']),
        'connected': json['connected'] == null ? undefined : json['connected'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'ipAddress': json['ip_address'] == null ? undefined : json['ip_address'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'ownerId': json['owner_id'] == null ? undefined : json['owner_id'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

  export function EntityThermometerToJSON(json: any): EntityThermometer {
      return EntityThermometerToJSONTyped(json, false);
  }

  export function EntityThermometerToJSONTyped(value?: EntityThermometer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': EntityThermometerConfigToJSON(value['config']),
        'connected': value['connected'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'ip_address': value['ipAddress'],
        'is_active': value['isActive'],
        'owner_id': value['ownerId'],
        'temperature': value['temperature'],
        'updated_at': value['updatedAt'],
    };
}

