/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SqliteTimeSeries } from './SqliteTimeSeries';
import {
    SqliteTimeSeriesFromJSON,
    SqliteTimeSeriesFromJSONTyped,
    SqliteTimeSeriesToJSON,
    SqliteTimeSeriesToJSONTyped,
} from './SqliteTimeSeries';

/**
 * 
 * @export
 * @interface SensorListSensorMetricLogsResponseData
 */
export interface SensorListSensorMetricLogsResponseData {
    /**
     * 
     * @type {Array<SqliteTimeSeries>}
     * @memberof SensorListSensorMetricLogsResponseData
     */
    avg?: Array<SqliteTimeSeries>;
    /**
     * 
     * @type {Array<SqliteTimeSeries>}
     * @memberof SensorListSensorMetricLogsResponseData
     */
    max?: Array<SqliteTimeSeries>;
    /**
     * 
     * @type {Array<SqliteTimeSeries>}
     * @memberof SensorListSensorMetricLogsResponseData
     */
    min?: Array<SqliteTimeSeries>;
}

/**
 * Check if a given object implements the SensorListSensorMetricLogsResponseData interface.
 */
export function instanceOfSensorListSensorMetricLogsResponseData(value: object): value is SensorListSensorMetricLogsResponseData {
    return true;
}

export function SensorListSensorMetricLogsResponseDataFromJSON(json: any): SensorListSensorMetricLogsResponseData {
    return SensorListSensorMetricLogsResponseDataFromJSONTyped(json, false);
}

export function SensorListSensorMetricLogsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorListSensorMetricLogsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'avg': json['avg'] == null ? undefined : ((json['avg'] as Array<any>).map(SqliteTimeSeriesFromJSON)),
        'max': json['max'] == null ? undefined : ((json['max'] as Array<any>).map(SqliteTimeSeriesFromJSON)),
        'min': json['min'] == null ? undefined : ((json['min'] as Array<any>).map(SqliteTimeSeriesFromJSON)),
    };
}

  export function SensorListSensorMetricLogsResponseDataToJSON(json: any): SensorListSensorMetricLogsResponseData {
      return SensorListSensorMetricLogsResponseDataToJSONTyped(json, false);
  }

  export function SensorListSensorMetricLogsResponseDataToJSONTyped(value?: SensorListSensorMetricLogsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg': value['avg'] == null ? undefined : ((value['avg'] as Array<any>).map(SqliteTimeSeriesToJSON)),
        'max': value['max'] == null ? undefined : ((value['max'] as Array<any>).map(SqliteTimeSeriesToJSON)),
        'min': value['min'] == null ? undefined : ((value['min'] as Array<any>).map(SqliteTimeSeriesToJSON)),
    };
}

