/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitySensor } from './EntitySensor';
import {
    EntitySensorFromJSON,
    EntitySensorFromJSONTyped,
    EntitySensorToJSON,
    EntitySensorToJSONTyped,
} from './EntitySensor';

/**
 * 
 * @export
 * @interface SensorCreateSensorResponse
 */
export interface SensorCreateSensorResponse {
    /**
     * 
     * @type {EntitySensor}
     * @memberof SensorCreateSensorResponse
     */
    data?: EntitySensor;
    /**
     * 
     * @type {number}
     * @memberof SensorCreateSensorResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SensorCreateSensorResponse interface.
 */
export function instanceOfSensorCreateSensorResponse(value: object): value is SensorCreateSensorResponse {
    return true;
}

export function SensorCreateSensorResponseFromJSON(json: any): SensorCreateSensorResponse {
    return SensorCreateSensorResponseFromJSONTyped(json, false);
}

export function SensorCreateSensorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorCreateSensorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : EntitySensorFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SensorCreateSensorResponseToJSON(json: any): SensorCreateSensorResponse {
      return SensorCreateSensorResponseToJSONTyped(json, false);
  }

  export function SensorCreateSensorResponseToJSONTyped(value?: SensorCreateSensorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EntitySensorToJSON(value['data']),
        'status': value['status'],
    };
}

