/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SensorCreateThermometerLogResponse
 */
export interface SensorCreateThermometerLogResponse {
    /**
     * 
     * @type {string}
     * @memberof SensorCreateThermometerLogResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof SensorCreateThermometerLogResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SensorCreateThermometerLogResponse interface.
 */
export function instanceOfSensorCreateThermometerLogResponse(value: object): value is SensorCreateThermometerLogResponse {
    return true;
}

export function SensorCreateThermometerLogResponseFromJSON(json: any): SensorCreateThermometerLogResponse {
    return SensorCreateThermometerLogResponseFromJSONTyped(json, false);
}

export function SensorCreateThermometerLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorCreateThermometerLogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SensorCreateThermometerLogResponseToJSON(json: any): SensorCreateThermometerLogResponse {
      return SensorCreateThermometerLogResponseToJSONTyped(json, false);
  }

  export function SensorCreateThermometerLogResponseToJSONTyped(value?: SensorCreateThermometerLogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

