/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitySensor } from './EntitySensor';
import {
    EntitySensorFromJSON,
    EntitySensorFromJSONTyped,
    EntitySensorToJSON,
    EntitySensorToJSONTyped,
} from './EntitySensor';

/**
 * 
 * @export
 * @interface SensorListSensorsResponse
 */
export interface SensorListSensorsResponse {
    /**
     * 
     * @type {Array<EntitySensor>}
     * @memberof SensorListSensorsResponse
     */
    data?: Array<EntitySensor>;
    /**
     * 
     * @type {number}
     * @memberof SensorListSensorsResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SensorListSensorsResponse interface.
 */
export function instanceOfSensorListSensorsResponse(value: object): value is SensorListSensorsResponse {
    return true;
}

export function SensorListSensorsResponseFromJSON(json: any): SensorListSensorsResponse {
    return SensorListSensorsResponseFromJSONTyped(json, false);
}

export function SensorListSensorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorListSensorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EntitySensorFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SensorListSensorsResponseToJSON(json: any): SensorListSensorsResponse {
      return SensorListSensorsResponseToJSONTyped(json, false);
  }

  export function SensorListSensorsResponseToJSONTyped(value?: SensorListSensorsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EntitySensorToJSON)),
        'status': value['status'],
    };
}

