/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorListSensorMetricLogsResponseData } from './SensorListSensorMetricLogsResponseData';
import {
    SensorListSensorMetricLogsResponseDataFromJSON,
    SensorListSensorMetricLogsResponseDataFromJSONTyped,
    SensorListSensorMetricLogsResponseDataToJSON,
    SensorListSensorMetricLogsResponseDataToJSONTyped,
} from './SensorListSensorMetricLogsResponseData';

/**
 * 
 * @export
 * @interface SensorListSensorMetricLogsResponse
 */
export interface SensorListSensorMetricLogsResponse {
    /**
     * 
     * @type {SensorListSensorMetricLogsResponseData}
     * @memberof SensorListSensorMetricLogsResponse
     */
    data?: SensorListSensorMetricLogsResponseData;
    /**
     * 
     * @type {number}
     * @memberof SensorListSensorMetricLogsResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SensorListSensorMetricLogsResponse interface.
 */
export function instanceOfSensorListSensorMetricLogsResponse(value: object): value is SensorListSensorMetricLogsResponse {
    return true;
}

export function SensorListSensorMetricLogsResponseFromJSON(json: any): SensorListSensorMetricLogsResponse {
    return SensorListSensorMetricLogsResponseFromJSONTyped(json, false);
}

export function SensorListSensorMetricLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorListSensorMetricLogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : SensorListSensorMetricLogsResponseDataFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SensorListSensorMetricLogsResponseToJSON(json: any): SensorListSensorMetricLogsResponse {
      return SensorListSensorMetricLogsResponseToJSONTyped(json, false);
  }

  export function SensorListSensorMetricLogsResponseToJSONTyped(value?: SensorListSensorMetricLogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SensorListSensorMetricLogsResponseDataToJSON(value['data']),
        'status': value['status'],
    };
}

