/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulatorUpdateThermometerConfigResponse
 */
export interface SimulatorUpdateThermometerConfigResponse {
    /**
     * 
     * @type {string}
     * @memberof SimulatorUpdateThermometerConfigResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof SimulatorUpdateThermometerConfigResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SimulatorUpdateThermometerConfigResponse interface.
 */
export function instanceOfSimulatorUpdateThermometerConfigResponse(value: object): value is SimulatorUpdateThermometerConfigResponse {
    return true;
}

export function SimulatorUpdateThermometerConfigResponseFromJSON(json: any): SimulatorUpdateThermometerConfigResponse {
    return SimulatorUpdateThermometerConfigResponseFromJSONTyped(json, false);
}

export function SimulatorUpdateThermometerConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorUpdateThermometerConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorUpdateThermometerConfigResponseToJSON(json: any): SimulatorUpdateThermometerConfigResponse {
      return SimulatorUpdateThermometerConfigResponseToJSONTyped(json, false);
  }

  export function SimulatorUpdateThermometerConfigResponseToJSONTyped(value?: SimulatorUpdateThermometerConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

