/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityThermometerConfig } from './EntityThermometerConfig';
import {
    EntityThermometerConfigFromJSON,
    EntityThermometerConfigFromJSONTyped,
    EntityThermometerConfigToJSON,
    EntityThermometerConfigToJSONTyped,
} from './EntityThermometerConfig';

/**
 * 
 * @export
 * @interface SimulatorUpdateThermometerConfigRequest
 */
export interface SimulatorUpdateThermometerConfigRequest {
    /**
     * 
     * @type {EntityThermometerConfig}
     * @memberof SimulatorUpdateThermometerConfigRequest
     */
    config?: EntityThermometerConfig;
}

/**
 * Check if a given object implements the SimulatorUpdateThermometerConfigRequest interface.
 */
export function instanceOfSimulatorUpdateThermometerConfigRequest(value: object): value is SimulatorUpdateThermometerConfigRequest {
    return true;
}

export function SimulatorUpdateThermometerConfigRequestFromJSON(json: any): SimulatorUpdateThermometerConfigRequest {
    return SimulatorUpdateThermometerConfigRequestFromJSONTyped(json, false);
}

export function SimulatorUpdateThermometerConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorUpdateThermometerConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : EntityThermometerConfigFromJSON(json['config']),
    };
}

  export function SimulatorUpdateThermometerConfigRequestToJSON(json: any): SimulatorUpdateThermometerConfigRequest {
      return SimulatorUpdateThermometerConfigRequestToJSONTyped(json, false);
  }

  export function SimulatorUpdateThermometerConfigRequestToJSONTyped(value?: SimulatorUpdateThermometerConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': EntityThermometerConfigToJSON(value['config']),
    };
}

