/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityThermometer } from './EntityThermometer';
import {
    EntityThermometerFromJSON,
    EntityThermometerFromJSONTyped,
    EntityThermometerToJSON,
    EntityThermometerToJSONTyped,
} from './EntityThermometer';

/**
 * 
 * @export
 * @interface SimulatorListThermometersResponse
 */
export interface SimulatorListThermometersResponse {
    /**
     * 
     * @type {Array<EntityThermometer>}
     * @memberof SimulatorListThermometersResponse
     */
    data?: Array<EntityThermometer>;
    /**
     * 
     * @type {number}
     * @memberof SimulatorListThermometersResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the SimulatorListThermometersResponse interface.
 */
export function instanceOfSimulatorListThermometersResponse(value: object): value is SimulatorListThermometersResponse {
    return true;
}

export function SimulatorListThermometersResponseFromJSON(json: any): SimulatorListThermometersResponse {
    return SimulatorListThermometersResponseFromJSONTyped(json, false);
}

export function SimulatorListThermometersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatorListThermometersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EntityThermometerFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function SimulatorListThermometersResponseToJSON(json: any): SimulatorListThermometersResponse {
      return SimulatorListThermometersResponseToJSONTyped(json, false);
  }

  export function SimulatorListThermometersResponseToJSONTyped(value?: SimulatorListThermometersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EntityThermometerToJSON)),
        'status': value['status'],
    };
}

