/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SqliteTimeSeries
 */
export interface SqliteTimeSeries {
    /**
     * 
     * @type {string}
     * @memberof SqliteTimeSeries
     */
    key?: string;
    /**
     * 
     * @type {object}
     * @memberof SqliteTimeSeries
     */
    timestamp?: object;
    /**
     * 
     * @type {number}
     * @memberof SqliteTimeSeries
     */
    value?: number;
}

/**
 * Check if a given object implements the SqliteTimeSeries interface.
 */
export function instanceOfSqliteTimeSeries(value: object): value is SqliteTimeSeries {
    return true;
}

export function SqliteTimeSeriesFromJSON(json: any): SqliteTimeSeries {
    return SqliteTimeSeriesFromJSONTyped(json, false);
}

export function SqliteTimeSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SqliteTimeSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

  export function SqliteTimeSeriesToJSON(json: any): SqliteTimeSeries {
      return SqliteTimeSeriesToJSONTyped(json, false);
  }

  export function SqliteTimeSeriesToJSONTyped(value?: SqliteTimeSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}

