/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityUserSetting } from './EntityUserSetting';
import {
    EntityUserSettingFromJSON,
    EntityUserSettingFromJSONTyped,
    EntityUserSettingToJSON,
    EntityUserSettingToJSONTyped,
} from './EntityUserSetting';

/**
 * 
 * @export
 * @interface UserGetMeSettingsResponse
 */
export interface UserGetMeSettingsResponse {
    /**
     * 
     * @type {Array<EntityUserSetting>}
     * @memberof UserGetMeSettingsResponse
     */
    data?: Array<EntityUserSetting>;
    /**
     * 
     * @type {number}
     * @memberof UserGetMeSettingsResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the UserGetMeSettingsResponse interface.
 */
export function instanceOfUserGetMeSettingsResponse(value: object): value is UserGetMeSettingsResponse {
    return true;
}

export function UserGetMeSettingsResponseFromJSON(json: any): UserGetMeSettingsResponse {
    return UserGetMeSettingsResponseFromJSONTyped(json, false);
}

export function UserGetMeSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGetMeSettingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EntityUserSettingFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function UserGetMeSettingsResponseToJSON(json: any): UserGetMeSettingsResponse {
      return UserGetMeSettingsResponseToJSONTyped(json, false);
  }

  export function UserGetMeSettingsResponseToJSONTyped(value?: UserGetMeSettingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EntityUserSettingToJSON)),
        'status': value['status'],
    };
}

