/* tslint:disable */
/* eslint-disable */
/**
 * Example API Doc
 * Describe your API
 *
 * The version of the OpenAPI document: SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityUser } from './EntityUser';
import {
    EntityUserFromJSON,
    EntityUserFromJSONTyped,
    EntityUserToJSON,
    EntityUserToJSONTyped,
} from './EntityUser';

/**
 * 
 * @export
 * @interface UserGetMeResponse
 */
export interface UserGetMeResponse {
    /**
     * 
     * @type {EntityUser}
     * @memberof UserGetMeResponse
     */
    data?: EntityUser;
    /**
     * 
     * @type {number}
     * @memberof UserGetMeResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the UserGetMeResponse interface.
 */
export function instanceOfUserGetMeResponse(value: object): value is UserGetMeResponse {
    return true;
}

export function UserGetMeResponseFromJSON(json: any): UserGetMeResponse {
    return UserGetMeResponseFromJSONTyped(json, false);
}

export function UserGetMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGetMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : EntityUserFromJSON(json['data']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function UserGetMeResponseToJSON(json: any): UserGetMeResponse {
      return UserGetMeResponseToJSONTyped(json, false);
  }

  export function UserGetMeResponseToJSONTyped(value?: UserGetMeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EntityUserToJSON(value['data']),
        'status': value['status'],
    };
}

